# Generated by Django 5.0.1 on 2024-02-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
