# Generated by Django 5.0.1 on 2024-02-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_slug_alter_service_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
